name: crimityapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  lottie: ^1.4.3

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  responsive: ^0.3.11+11
  flutter_login: ^4.1.1
  google_fonts: ^4.0.3
  getwidget: ^3.0.1
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.2.5
  location: ^4.4.0
  flutter_cache_manager: ^3.1.2
  permission_handler: ^6.1.3
  geolocator: ^8.0.1
  animated_splash_screen: ^1.3.0
  liquid_swipe: ^3.1.0
  get: ^4.6.5
  smooth_page_indicator: ^1.1.0
  line_awesome_flutter: ^2.0.0
  fl_chart: ^0.62.0
  url_launcher: ^6.1.10
  geocoding: ^2.1.0
  custom_info_window: ^1.0.1
  flutter_slidable: ^0.6.0
  sizer: ^2.0.15
  image_picker: ^0.8.7+4
  comment_box: ^0.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/imgs/ladron.png
    - images/amplify.png
  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
